// Copyright (c) 2026 Huawei Technologies Co., Ltd.
// This program is free software, you can redistribute it and/or modify it under the terms and conditions of
// CANN Open Software License Agreement Version 2.0 (the "License").
// Please refer to the License for details. You may not use this file except in compliance with the License.
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
// See LICENSE in the root of the software repository for the full text of the License.

// -----------------------------------------------------------------------------
// case: kernels/print-compute
// family: kernels
// target_ops: pto.print, pto.mte_gm_ub, pto.mte_ub_gm
// scenarios: print-plus-compute-coexistence, gm-ub-roundtrip-with-print,
//            integration-smoke-test
//
// This test verifies that pto.print can coexist with data-transfer ops
// (mte_gm_ub, mte_ub_gm) in a single kernel compiled through the standard
// PTOAS fatobj pipeline.  The kernel loads 64 f32 values from GM to UB,
// prints two diagnostic scalars via DebugTunnel, then stores the UB buffer
// to the output GM pointer.  The host compares the output buffer against
// the input — a correct passthrough confirms the pipeline works.
// -----------------------------------------------------------------------------
#include "test_common.h"
#include "acl/acl.h"
#include <cstdio>
#include <cstdlib>

using namespace PtoTestCommon;

#define ACL_CHECK(expr)                                                                          \
    do {                                                                                         \
        const aclError _ret = (expr);                                                            \
        if (_ret != ACL_SUCCESS) {                                                               \
            std::fprintf(stderr, "[ERROR] %s failed: %d (%s:%d)\n", #expr, (int)_ret, __FILE__, __LINE__); \
            const char *_recent = aclGetRecentErrMsg();                                          \
            if (_recent != nullptr && _recent[0] != '\0')                                        \
                std::fprintf(stderr, "[ERROR] RecentErrMsg: %s\n", _recent);                     \
            rc = 1;                                                                              \
            goto cleanup;                                                                        \
        }                                                                                        \
    } while (0)

void LaunchPrint_compute_kernel_mix_aiv(float *v1, float *v2,
                                         float v3, int32_t v4,
                                         void *stream);

int main() {
    constexpr size_t kElemCount = 64;
    constexpr size_t kFileSize = kElemCount * sizeof(float);
    float offsetHost = 1.5f;
    int32_t nHost = static_cast<int32_t>(kElemCount);

    float *v1Host = nullptr, *v2Host = nullptr;
    float *v1Device = nullptr, *v2Device = nullptr;

    int rc = 0;
    bool aclInited = false;
    bool deviceSet = false;
    int deviceId = 0;
    aclrtStream stream = nullptr;
    size_t fileSize = 0;

    ACL_CHECK(aclInit(nullptr));
    aclInited = true;
    if (const char *envDevice = std::getenv("ACL_DEVICE_ID"))
        deviceId = std::atoi(envDevice);
    ACL_CHECK(aclrtSetDevice(deviceId));
    deviceSet = true;
    ACL_CHECK(aclrtCreateStream(&stream));

    ACL_CHECK(aclrtMallocHost((void **)(&v1Host), kFileSize));
    ACL_CHECK(aclrtMallocHost((void **)(&v2Host), kFileSize));

    ACL_CHECK(aclrtMalloc((void **)&v1Device, kFileSize, ACL_MEM_MALLOC_HUGE_FIRST));
    ACL_CHECK(aclrtMalloc((void **)&v2Device, kFileSize, ACL_MEM_MALLOC_HUGE_FIRST));

    // Read input data generated by golden.py
    if (!ReadFile("./v1.bin", fileSize, v1Host, kFileSize) || fileSize != kFileSize) {
        std::fprintf(stderr, "[ERROR] Failed to read ./v1.bin (expected %zu bytes, got %zu)\n",
                     kFileSize, fileSize);
        rc = 1;
        goto cleanup;
    }

    ACL_CHECK(aclrtMemcpy(v1Device, kFileSize, v1Host, kFileSize, ACL_MEMCPY_HOST_TO_DEVICE));

    // Launch kernel: print + passthrough copy (input -> output via UB)
    LaunchPrint_compute_kernel_mix_aiv(v1Device, v2Device, offsetHost, nHost, stream);

    ACL_CHECK(aclrtSynchronizeStream(stream));
    ACL_CHECK(aclrtMemcpy(v2Host, kFileSize, v2Device, kFileSize, ACL_MEMCPY_DEVICE_TO_HOST));
    WriteFile("./v2.bin", v2Host, kFileSize);

cleanup:
    aclrtFree(v1Device); aclrtFree(v2Device);
    aclrtFreeHost(v1Host); aclrtFreeHost(v2Host);
    if (stream != nullptr) {
        const aclError _ret = aclrtDestroyStream(stream);
        if (_ret != ACL_SUCCESS)
            std::fprintf(stderr, "[ERROR] %s failed: %d (%s:%d)\n",
                         "aclrtDestroyStream(stream)", (int)_ret, __FILE__, __LINE__);
    }
    if (deviceSet) {
        const aclError _ret = aclrtResetDevice(deviceId);
        if (_ret != ACL_SUCCESS)
            std::fprintf(stderr, "[ERROR] %s failed: %d (%s:%d)\n",
                         "aclrtResetDevice(deviceId)", (int)_ret, __FILE__, __LINE__);
    }
    if (aclInited) {
        const aclError _ret = aclFinalize();
        if (_ret != ACL_SUCCESS)
            std::fprintf(stderr, "[ERROR] %s failed: %d (%s:%d)\n",
                         "aclFinalize()", (int)_ret, __FILE__, __LINE__);
    }

    return rc;
}
